version: '3'
services:
  postgresql:
    container_name: postgresql
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_USERNAME=jakub
      - POSTGRESQL_DATABASE=data_db
      - POSTGRESQL_PASSWORD=pass
    ports:
      - 5432:5432

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    network_mode: host
    container_name: grafana
    restart: unless-stopped
    volumes:
      - ./docker/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./docker/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - 3000:3000
  tempo:
    container_name: tempo
    image: grafana/tempo
#    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    command: [ '-config.file=/etc/tempo.yml' ]
    volumes:
      - ./docker/grafana/tempo.yml:/etc/tempo.yml:ro
      - ./docker/tempo-data/:/tmp/tempo
    ports:
      - 3200:3200    # tempo
  loki:
    container_name: loki
    image: grafana/loki
#    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    command: [ '-config.file=/etc/loki/local-config.yaml' ]
    ports:
      - 3100:3100

